[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pytest-aioboto3"
version = "0.1.0"
description = "Aioboto3 Pytest with Moto"
authors = ["Shipwell Engineering", "Phillip Verheyden"]

[tool.poetry.dependencies]
python = "^3.7"
aioboto3 = "^9.5.0"
moto = {extras = ["s3", "server"], version = "^3.1.6"}
types-aiobotocore = {extras = ["s3"], version = "^2.2.0"}
requests = "^2.0"
types-aiobotocore-s3 = "2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
boto3-stubs = {extras = ["s3"], version = "^1.22.2"}
pytest-asyncio = "^0.18.3"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
filterwarnings = [
    'error', # treat all warnings as errors
]
asyncio_mode = "auto"

[tool.poetry.plugins."pytest11"]
pytest-aioboto3 = 'pytest_aioboto3'
